name: publishing-net

on:
  push:
    branches: ["main"]

jobs:
  # build-and-deploy-identityserver-webapp:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 8.0.x

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./src/Services/IdentityServer/IdentityServer.WebApp/Dockerfile
  #         push: true
  #         tags: zcqiand/identityserver-webapp:latest

  #     - name: ssh login and pull Docker image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.CLOUD_IP }}
  #         username: ${{ secrets.CLOUD_NAME }}
  #         password: ${{ secrets.CLOUD_PASSWORD }}
  #         script: cd /home/app/hejing && sudo sh identityserver-webapp.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

  # build-and-deploy-identityserver-testclient1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 8.0.x

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./src/Services/IdentityServer/IdentityServer.TestClient1/Dockerfile
  #         push: true
  #         tags: zcqiand/identityserver-testclient1:latest

  #     - name: ssh login and pull Docker image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.CLOUD_IP }}
  #         username: ${{ secrets.CLOUD_NAME }}
  #         password: ${{ secrets.CLOUD_PASSWORD }}
  #         script: cd /home/app/hejing && sudo sh identityserver-testclient1.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

  # build-and-deploy-identityserver-testapi1:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 8.0.x

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v3
  #       with:
  #         username: ${{ secrets.DOCKER_USERNAME }}
  #         password: ${{ secrets.DOCKER_PASSWORD }}

  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: ./src/Services/IdentityServer/IdentityServer.TestApi1/Dockerfile
  #         push: true
  #         tags: zcqiand/identityserver-testapi1:latest

  #     - name: ssh login and pull Docker image
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.CLOUD_IP }}
  #         username: ${{ secrets.CLOUD_NAME }}
  #         password: ${{ secrets.CLOUD_PASSWORD }}
  #         script: cd /home/app/hejing && sudo sh identityserver-testapi1.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

  build-and-deploy-commonserver-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./src/Services/CommonServer/CommonServer.API/Dockerfile
          push: true
          tags: zcqiand/commonserver-api:latest

      - name: ssh login and pull Docker image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.CLOUD_IP }}
          username: ${{ secrets.CLOUD_NAME }}
          password: ${{ secrets.CLOUD_PASSWORD }}
          script: cd /home/app/hejing && sudo sh commonserver-api.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}

  # build-and-deploy-nuget:
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 5
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3

  #     - name: Setup .NET
  #       uses: actions/setup-dotnet@v3
  #       with:
  #         dotnet-version: 8.0.x

  #     - name: Build
  #       run:  |
  #           dotnet build src/Infrastructure/**/CommonMormon.Infrastructure.csproj --configuration Release
  #           dotnet build src/Infrastructure/**/CommonMormon.Infrastructure.API.csproj --configuration Release
  #           dotnet build src/Infrastructure/**/CommonMormon.Infrastructure.Shared.csproj --configuration Release

  #     - name: Pack nugets
  #       run:  |
  #           dotnet pack src/Infrastructure/**/CommonMormon.Infrastructure.csproj --configuration Release --output ./nuget
  #           dotnet pack src/Infrastructure/**/CommonMormon.Infrastructure.API.csproj --configuration Release --output ./nuget
  #           dotnet pack src/Infrastructure/**/CommonMormon.Infrastructure.Shared.csproj --configuration Release --output ./nuget

  #     - name: Push to NuGet
  #       run: dotnet nuget push ./nuget/*.nupkg --api-key ${{secrets.NUGET_APIKEY}} --source https://api.nuget.org/v3/index.json